import { defineConfig } from 'vitepress'

export default defineConfig({
  title: '装修知识库',
  description: '汇集各类装修知识，为从业者和业主提供专业参考',
  lang: 'zh-CN',

  themeConfig: {
    logo: '/logo.svg',

    nav: [
      { text: '首页', link: '/' },
      { text: '装修白皮书', link: '/whitepaper/' },
      { text: '施工规范', link: '/standards/' },
      { text: '家装模式', link: '/models/' },
      { text: '工种工艺', link: '/crafts/' },
      { text: '报价预算', link: '/pricing/' },
      { text: '验收标准', link: '/inspection/' },
      { text: '材料指南', link: '/materials/' },
      { text: '避坑指南', link: '/pitfalls/' },
      { text: '市场分析', link: '/market/' },
      { text: '龙头企业', link: '/enterprises/' },
    ],

    sidebar: {
      '/whitepaper/': [
        {
          text: '装修白皮书',
          items: [
            { text: '概述', link: '/whitepaper/' },
            { text: '行业白皮书解读', link: '/whitepaper/industry-whitepaper' },
            { text: '概述详解', link: '/whitepaper/overview' },
            { text: '行业发展趋势', link: '/whitepaper/trends' },
            { text: '装修全流程指南', link: '/whitepaper/process' },
            { text: '装修风格大全', link: '/whitepaper/styles' },
            { text: '旧房翻新指南', link: '/whitepaper/renovation' },
            { text: '旧房翻新详解', link: '/whitepaper/renovation-detailed' },
            { text: '节能装修指南', link: '/whitepaper/energy-saving' },
            { text: '环保装修指南', link: '/whitepaper/environmental' },
            { text: '环保装修设计', link: '/whitepaper/eco-design' },
            { text: '甲醛治理指南', link: '/whitepaper/formaldehyde' },
            { text: '智能家居装修', link: '/whitepaper/smarthome' },
            { text: '装修季节选择', link: '/whitepaper/season' },
            { text: '装修时间规划', link: '/whitepaper/timeline' },
            { text: '装修注意事项', link: '/whitepaper/checklist' },
            { text: '装修注意事项详解', link: '/whitepaper/attention' },
            { text: '装修收尾工作', link: '/whitepaper/finishing' },
            { text: '出租房装修指南', link: '/whitepaper/rental' },
            { text: '装修开工仪式', link: '/whitepaper/ceremony' },
            { text: '装修竣工验收', link: '/whitepaper/cleaning' },
            { text: '装修入住指南', link: '/whitepaper/move-in' },
            { text: '装修售后服务', link: '/whitepaper/after-sales' },
            { text: '装修常见问题', link: '/whitepaper/faq' },
            { text: '装修风水指南', link: '/whitepaper/fengshui' },
            { text: '装修进度模板', link: '/whitepaper/schedule-template' },
            { text: '装修专业术语', link: '/whitepaper/terminology' },
            { text: '装修保修指南', link: '/whitepaper/warranty' },
            { text: '业主自检指南', link: '/whitepaper/inspection-self' },
            { text: '装修审批流程', link: '/whitepaper/permit' },
            { text: '邻里关系处理', link: '/whitepaper/neighbor' },
            { text: '施工队选择', link: '/whitepaper/contractor-select' },
            { text: '装修词汇表', link: '/whitepaper/glossary' },
          ],
        },
      ],
      '/standards/': [
        {
          text: '施工规范',
          items: [
            { text: '概述', link: '/standards/' },
            { text: '规范概述', link: '/standards/overview' },
            { text: '施工流程', link: '/standards/process-flow' },
            { text: '施工阶段', link: '/standards/phases' },
            { text: '常见问题', link: '/standards/common-issues' },
            { text: '规范详解', link: '/standards/detailed' },
            { text: '国家标准规范', link: '/standards/national/' },
            { text: 'GB50210验收标准解读', link: '/standards/national/GB50210' },
            { text: 'GB50327施工规范解读', link: '/standards/national/GB50327' },
            { text: 'GB50325环保标准解读', link: '/standards/national/GB50325' },
            { text: 'GB50222防火规范解读', link: '/standards/national/GB50222' },
            { text: 'GB50242给排水验收解读', link: '/standards/national/GB50242' },
            { text: 'GB50303电气验收解读', link: '/standards/national/GB50303' },
            { text: '行业标准汇总', link: '/standards/national/industry-standards' },
            { text: '地方配套标准', link: '/standards/national/local-standards' },
            { text: '国家标准详解', link: '/standards/national/attention' },
            { text: '拆改工程规范', link: '/standards/national/demolition' },
            { text: '质量管理规范', link: '/standards/national/quality' },
            { text: '绿色环保标准', link: '/standards/national/green' },
            { text: '安全施工规范', link: '/standards/national/safety' },
            { text: '安全施工详解', link: '/standards/national/safety-standard' },
            { text: '材料验收标准', link: '/standards/national/material-inspection' },
            { text: '材料存储规范', link: '/standards/national/material-storage' },
            { text: '噪音控制标准', link: '/standards/national/noise-control' },
            { text: '垃圾处理标准', link: '/standards/national/waste-management' },
            { text: '成品保护标准', link: '/standards/national/protection' },
            { text: '无障碍标准', link: '/standards/national/accessibility' },
            { text: '施工队管理', link: '/standards/national/team-management' },
            { text: '消防安全标准', link: '/standards/national/fire-safety' },
            { text: '水电工程规范', link: '/standards/hydro-electric/' },
            { text: '水电工种施工指南', link: '/standards/hydro-electric/guide' },
            { text: '水电施工标准', link: '/standards/hydro-electric/standard' },
            { text: '水电测试标准', link: '/standards/hydro-electric/testing' },
            { text: '燃气管道标准', link: '/standards/hydro-electric/gas' },
            { text: '智能家居布线', link: '/standards/hydro-electric/smart-home-wiring' },
            { text: '电路施工详解', link: '/standards/hydro-electric/electrical' },
            { text: '电路施工详解', link: '/standards/hydro-electric/electrical-detailed' },
            { text: '水路施工详解', link: '/standards/hydro-electric/plumbing' },
            { text: '水路施工详解', link: '/standards/hydro-electric/plumbing-detailed' },
            { text: '水电改造详解', link: '/standards/hydro-electric/renovation' },
            { text: '泥瓦工程规范', link: '/standards/masonry/' },
            { text: '泥瓦工种施工指南', link: '/standards/masonry/guide' },
            { text: '泥瓦施工标准', link: '/standards/masonry/standard' },
            { text: '泥瓦施工详解', link: '/standards/masonry/bathroom' },
            { text: '地面找平标准', link: '/standards/masonry/leveling' },
            { text: '防水施工详解', link: '/standards/masonry/waterproof' },
            { text: '防水施工标准', link: '/standards/masonry/waterproof-standard' },
            { text: '卫生间防水详解', link: '/standards/masonry/bathroom-waterproof' },
            { text: '瓷砖铺贴规范', link: '/standards/masonry/tiles' },
            { text: '石材铺贴标准', link: '/standards/masonry/stone' },
            { text: '木作工程规范', link: '/standards/carpentry/' },
            { text: '木作工种施工指南', link: '/standards/carpentry/guide' },
            { text: '木作施工标准', link: '/standards/carpentry/standard' },
            { text: '吊顶施工规范', link: '/standards/carpentry/ceiling' },
            { text: '油漆工程规范', link: '/standards/painting/' },
            { text: '油漆工种施工指南', link: '/standards/painting/guide' },
            { text: '油漆施工标准', link: '/standards/painting/standard' },
            { text: '腻子施工标准', link: '/standards/painting/putty' },
            { text: '墙面处理规范', link: '/standards/painting/wall' },
            { text: '墙面处理详解', link: '/standards/painting/wall-detailed' },
            { text: '墙面处理详解', link: '/standards/painting/detailed' },
            { text: '安装工程规范', link: '/standards/installation/' },
            { text: '安装施工标准', link: '/standards/installation/standard' },
            { text: '地板安装规范', link: '/standards/installation/flooring' },
            { text: '橱柜安装规范', link: '/standards/installation/cabinet' },
            { text: '厨房安装规范', link: '/standards/installation/kitchen' },
            { text: '卫浴安装规范', link: '/standards/installation/sanitary' },
            { text: '门窗安装规范', link: '/standards/installation/doors' },
            { text: '照明安装规范', link: '/standards/installation/lighting' },
          ],
        },
      ],
      '/models/': [
        {
          text: '家装模式',
          items: [
            { text: '概述', link: '/models/' },
            { text: '模式对比', link: '/models/comparison' },
            { text: '清包', link: '/models/qingbao' },
            { text: '半包', link: '/models/banbao' },
            { text: '全包', link: '/models/quanbao' },
            { text: '整装', link: '/models/zhengzhuang' },
            { text: '拎包入住', link: '/models/ruzhujike' },
            { text: '装配式装修', link: '/models/prefabricated' },
          ],
        },
      ],
      '/crafts/': [
        {
          text: '工种工艺',
          items: [
            { text: '概述', link: '/crafts/' },
            { text: '水电工工艺', link: '/crafts/hydro-electric/' },
            { text: '水电工施工流程', link: '/crafts/hydro-electric/process' },
            { text: '水电布线详解', link: '/crafts/hydro-electric/wiring' },
            { text: '泥瓦工工艺', link: '/crafts/masonry/' },
            { text: '泥瓦工施工流程', link: '/crafts/masonry/process' },
            { text: '瓷砖铺贴详解', link: '/crafts/masonry/tiles-detailed' },
            { text: '美缝工艺详解', link: '/crafts/masonry/grouting' },
            { text: '木工工艺', link: '/crafts/carpentry/' },
            { text: '木工施工流程', link: '/crafts/carpentry/process' },
            { text: '木工工艺详解', link: '/crafts/carpentry/detailed' },
            { text: '吊顶工艺详解', link: '/crafts/carpentry/ceiling-detailed' },
            { text: '油漆工工艺', link: '/crafts/painting/' },
            { text: '油漆工施工流程', link: '/crafts/painting/process' },
            { text: '油漆工艺详解', link: '/crafts/painting/detailed' },
            { text: '安装工工艺', link: '/crafts/installation/' },
            { text: '安装工施工流程', link: '/crafts/installation/process' },
            { text: '厨房装修工艺', link: '/crafts/kitchen' },
            { text: '厨房台面工艺', link: '/crafts/kitchen/countertop' },
            { text: '厨房装修详解', link: '/crafts/kitchen-detailed' },
            { text: '卫生间装修工艺', link: '/crafts/bathroom' },
            { text: '卫生间通风工艺', link: '/crafts/bathroom/ventilation' },
            { text: '卫生间装修详解', link: '/crafts/bathroom-detailed' },
            { text: '墙面瓷砖工艺', link: '/crafts/wall-tiles' },
            { text: '定制柜安装工艺', link: '/crafts/cabinet-install' },
            { text: '隔音施工工艺', link: '/crafts/soundproofing' },
            { text: '客厅装修工艺', link: '/crafts/living-room' },
            { text: '卧室装修工艺', link: '/crafts/bedroom' },
            { text: '餐厅装修工艺', link: '/crafts/dining-room' },
            { text: '地面找平工艺', link: '/crafts/floor-leveling' },
            { text: '排水系统工艺', link: '/crafts/drainage' },
            { text: '厨房防溅墙工艺', link: '/crafts/backsplash' },
            { text: '玄关装修工艺', link: '/crafts/entrance' },
            { text: '书房装修工艺', link: '/crafts/study-room' },
            { text: '儿童房装修工艺', link: '/crafts/kids-room' },
            { text: '楼梯装修工艺', link: '/crafts/stairs' },
            { text: '配电箱工艺', link: '/crafts/electrical-panel' },
            { text: '地暖施工工艺', link: '/crafts/floor-heating' },
            { text: '照明设计', link: '/crafts/lighting' },
            { text: '暖通与中央空调', link: '/crafts/hvac' },
            { text: '新风系统', link: '/crafts/fresh-air' },
            { text: '水路系统', link: '/crafts/water-system' },
            { text: '暖气系统', link: '/crafts/heating' },
            { text: '收纳设计', link: '/crafts/storage' },
            { text: '阳台装修工艺', link: '/crafts/balcony' },
            { text: '软装搭配', link: '/crafts/soft-decor' },
            { text: '色彩搭配', link: '/crafts/color' },
            { text: '智能家居工艺', link: '/crafts/smart-home' },
            { text: '小户型装修', link: '/crafts/small-apartment' },
            { text: '大户型装修', link: '/crafts/large-apartment' },
            { text: '别墅装修', link: '/crafts/villa' },
          ],
        },
      ],
      '/pricing/': [
        {
          text: '报价与预算',
          items: [
            { text: '概述', link: '/pricing/' },
            { text: '报价规划', link: '/pricing/planning' },
            { text: '报价清单模板', link: '/pricing/template' },
            { text: '报价详解', link: '/pricing/quotation' },
            { text: '各城市参考价', link: '/pricing/city-price' },
            { text: '预算控制技巧', link: '/pricing/budget-tips' },
            { text: '预算详细指南', link: '/pricing/budget-guide' },
            { text: '预算模板', link: '/pricing/budget-template' },
            { text: '预算控制', link: '/pricing/budget-control' },
            { text: '装修面积计算', link: '/pricing/area' },
            { text: '装修贷款', link: '/pricing/loan' },
            { text: '二手房装修预算', link: '/pricing/second-hand' },
            { text: '装修贷款详解', link: '/pricing/loan-detailed' },
            { text: '家具家电配置', link: '/pricing/appliance' },
            { text: '装修省钱技巧', link: '/pricing/money-saving' },
            { text: '隐藏费用揭秘', link: '/pricing/hidden-costs' },
            { text: '经济型报价模板', link: '/pricing/template-economy' },
            { text: '舒适型报价模板', link: '/pricing/template-comfort' },
            { text: '高端型报价模板', link: '/pricing/template-premium' },
          ],
        },
      ],
      '/inspection/': [
        {
          text: '验收标准',
          items: [
            { text: '概述', link: '/inspection/' },
            { text: '验收指南', link: '/inspection/guide' },
            { text: '验收标准', link: '/inspection/standard' },
            { text: '验收标准详解', link: '/inspection/standards' },
            { text: '验收流程', link: '/inspection/process' },
            { text: '验收注意事项', link: '/inspection/attention' },
            { text: '环保验收', link: '/inspection/environmental' },
            { text: '验收工具清单', link: '/inspection/tools' },
            { text: '室内空气验收', link: '/inspection/air-quality' },
            { text: '水电验收', link: '/inspection/hydro-electric' },
            { text: '水电验收详细清单', link: '/inspection/hydro-electric-checklist-detailed' },
            { text: '水电验收标准', link: '/inspection/hydro-electric/standard' },
            { text: '水电验收清单', link: '/inspection/hydro-electric/checklist' },
            { text: '泥瓦验收', link: '/inspection/masonry' },
            { text: '泥瓦验收详细清单', link: '/inspection/masonry-checklist-detailed' },
            { text: '泥瓦验收清单', link: '/inspection/masonry/checklist' },
            { text: '木作验收', link: '/inspection/carpentry' },
            { text: '木作验收详细清单', link: '/inspection/carpentry-checklist-detailed' },
            { text: '木作验收清单', link: '/inspection/carpentry/checklist' },
            { text: '油漆验收', link: '/inspection/painting' },
            { text: '油漆验收详细清单', link: '/inspection/painting-checklist-detailed' },
            { text: '油漆验收清单', link: '/inspection/painting/checklist' },
            { text: '安装验收清单', link: '/inspection/installation/checklist' },
            { text: '竣工验收', link: '/inspection/final' },
            { text: '竣工验收详细清单', link: '/inspection/final-checklist-detailed' },
            { text: '竣工验收标准', link: '/inspection/final/standard' },
            { text: '竣工验收清单', link: '/inspection/final/checklist' },
          ],
        },
      ],
      '/materials/': [
        {
          text: '材料指南',
          items: [
            { text: '概述', link: '/materials/' },
            { text: '材料对比', link: '/materials/comparison' },
            { text: '采购指南', link: '/materials/purchase-guide' },
            { text: '品牌指南', link: '/materials/brand-guide' },
            { text: '主材清单', link: '/materials/main' },
            { text: '主材详解', link: '/materials/main-detailed' },
            { text: '辅材清单', link: '/materials/auxiliary' },
            { text: '辅材详解', link: '/materials/auxiliary-detailed' },
            { text: '品牌推荐', link: '/materials/brands' },
            { text: '材料鉴别', link: '/materials/identify' },
            { text: '环保材料', link: '/materials/eco-materials' },
            { text: '环保材料详解', link: '/materials/eco-detailed' },
            { text: '水管电线管材', link: '/materials/pipe-types' },
            { text: '胶水与粘合剂', link: '/materials/adhesive' },
            { text: '保温隔热材料', link: '/materials/insulation' },
            { text: '台面材料选购', link: '/materials/countertop' },
            { text: '智能家居预埋', link: '/materials/smart-home' },
            { text: '瓷砖选购', link: '/materials/tiles' },
            { text: '瓷砖选购详解', link: '/materials/tiles-guide' },
            { text: '瓷砖种类', link: '/materials/tile-types' },
            { text: '地板选购', link: '/materials/flooring' },
            { text: '地板种类', link: '/materials/floor-types' },
            { text: '室内门选购', link: '/materials/doors' },
            { text: '卫浴选购', link: '/materials/bathroom' },
            { text: '涂料选购', link: '/materials/paint' },
            { text: '全屋定制', link: '/materials/custom-furniture' },
            { text: '全屋定制详解', link: '/materials/custom-detailed' },
            { text: '橱柜选购', link: '/materials/cabinet' },
            { text: '五金选购', link: '/materials/hardware' },
            { text: '窗帘选购', link: '/materials/curtain' },
            { text: '灯具选购', link: '/materials/lighting' },
            { text: '家电尺寸预留', link: '/materials/appliances' },
            { text: '密封材料', link: '/materials/sealant' },
            { text: '窗户选购', link: '/materials/windows' },
            { text: '墙面材料对比', link: '/materials/wall-materials' },
            { text: '采购清单', link: '/materials/checklist' },
            { text: '材料采购清单', link: '/materials/purchase-checklist' },
          ],
        },
      ],
      '/pitfalls/': [
        {
          text: '避坑指南',
          items: [
            { text: '概述', link: '/pitfalls/' },
            { text: '装修前避坑', link: '/pitfalls/pre-renovation' },
            { text: '避坑指南总览', link: '/pitfalls/guide' },
            { text: '避坑清单', link: '/pitfalls/checklist' },
            { text: '装修队选择', link: '/pitfalls/team' },
            { text: '装修公司选择', link: '/pitfalls/company' },
            { text: '设计阶段避坑', link: '/pitfalls/design/' },
            { text: '设计避坑详解', link: '/pitfalls/design/detailed' },
            { text: '施工阶段避坑', link: '/pitfalls/construction/' },
            { text: '施工中避坑', link: '/pitfalls/construction-pitfalls' },
            { text: '施工避坑详解', link: '/pitfalls/construction/detailed' },
            { text: '施工变更避坑', link: '/pitfalls/construction/changes' },
            { text: '付款方式避坑', link: '/pitfalls/construction/payment' },
            { text: '成品保护', link: '/pitfalls/construction/protection' },
            { text: '垃圾清运', link: '/pitfalls/construction/garbage' },
            { text: '工期管理', link: '/pitfalls/construction/schedule' },
            { text: '装修噪音', link: '/pitfalls/construction/noise' },
            { text: '装修垃圾处理', link: '/pitfalls/construction/waste' },
            { text: '沟通陷阱避坑', link: '/pitfalls/communication' },
            { text: '季节性装修避坑', link: '/pitfalls/seasonal' },
            { text: '设计费避坑', link: '/pitfalls/design-fee' },
            { text: '材料替换避坑', link: '/pitfalls/materials/substitution' },
            { text: '保修期避坑', link: '/pitfalls/warranty' },
            { text: '家电采购避坑', link: '/pitfalls/appliance' },
            { text: '灯具采购避坑', link: '/pitfalls/lighting' },
            { text: '验收环节避坑', link: '/pitfalls/acceptance' },
            { text: '材料采购避坑', link: '/pitfalls/materials/' },
            { text: '材料真伪鉴别', link: '/pitfalls/material-authentication' },
            { text: '材料验收', link: '/pitfalls/materials/inspection' },
            { text: '材料采购详解', link: '/pitfalls/materials/purchase' },
            { text: '材料存储', link: '/pitfalls/materials/storage' },
            { text: '合同陷阱避坑', link: '/pitfalls/contract/' },
            { text: '签合同避坑', link: '/pitfalls/contract-signing' },
            { text: '合同陷阱详解', link: '/pitfalls/contract/traps' },
            { text: '附加条款避坑', link: '/pitfalls/contract/addition' },
            { text: '合同管理', link: '/pitfalls/contract/management' },
            { text: '合同范本', link: '/pitfalls/contract/sample' },
            { text: '合同模板', link: '/pitfalls/contract/template' },
            { text: '报价单陷阱', link: '/pitfalls/contract/quotation' },
            { text: '合同审查', link: '/pitfalls/contract/review' },
            { text: '合同审查清单', link: '/pitfalls/contract/review-checklist' },
            { text: '装修监理', link: '/pitfalls/supervision' },
            { text: '装修监理详解', link: '/pitfalls/supervision-detailed' },
            { text: '装修保险', link: '/pitfalls/insurance' },
            { text: '装修纠纷处理', link: '/pitfalls/dispute' },
            { text: '验收与售后避坑', link: '/pitfalls/acceptance-after-sales' },
            { text: '物业装修规定', link: '/pitfalls/property' },
            { text: '装修法律问题', link: '/pitfalls/legal' },
          ],
        },
      ],
      '/market/': [
        {
          text: '市场分析',
          items: [
            { text: '概述', link: '/market/' },
            { text: '市场概览', link: '/market/overview' },
            { text: '行业发展历程', link: '/market/history' },
            { text: '未来趋势', link: '/market/future' },
            { text: '北京市场', link: '/market/beijing' },
            { text: '北京市场详解', link: '/market/beijing-detailed' },
            { text: '上海市场', link: '/market/shanghai' },
            { text: '上海市场详解', link: '/market/shanghai-detailed' },
            { text: '广州市场', link: '/market/guangzhou' },
            { text: '深圳市场', link: '/market/shenzhen' },
            { text: '杭州市场', link: '/market/hangzhou' },
            { text: '成都市场', link: '/market/chengdu' },
            { text: '武汉市场', link: '/market/wuhan' },
            { text: '南京市场', link: '/market/nanjing' },
            { text: '西安市场', link: '/market/xian' },
            { text: '重庆市场', link: '/market/chongqing' },
            { text: '天津市场', link: '/market/tianjin' },
            { text: '青岛市场', link: '/market/qingdao' },
            { text: '苏州市场', link: '/market/suzhou' },
            { text: '长沙市场', link: '/market/changsha' },
            { text: '郑州市场', link: '/market/zhengzhou' },
            { text: '厦门市场', link: '/market/xiamen' },
            { text: '济南市场', link: '/market/jinan' },
            { text: '大连市场', link: '/market/dalian' },
            { text: '福州市场', link: '/market/fuzhou' },
            { text: '合肥市场', link: '/market/hefei' },
            { text: '哈尔滨市场', link: '/market/harbin' },
            { text: '太原市场', link: '/market/taiyuan' },
            { text: '石家庄市场', link: '/market/shijiazhuang' },
            { text: '南宁市场', link: '/market/nanning' },
            { text: '南昌市场', link: '/market/nanchang' },
            { text: '贵阳市场', link: '/market/guiyang' },
            { text: '更多城市市场分析', link: '/market/more-cities' },
          ],
        },
      ],
      '/enterprises/': [
        {
          text: '龙头企业',
          items: [
            { text: '概述', link: '/enterprises/' },
            { text: '企业发展现状', link: '/enterprises/status' },
            { text: '企业发展趋势', link: '/enterprises/trends' },
            { text: '对比分析', link: '/enterprises/comparison' },
            { text: '东易日盛', link: '/enterprises/dongyirisheng' },
            { text: '业之峰', link: '/enterprises/yeezone' },
            { text: '金螳螂家', link: '/enterprises/goldmantis' },
            { text: '名雕装饰', link: '/enterprises/mingdiao' },
            { text: '定制家居企业', link: '/enterprises/custom-home' },
            { text: '建材龙头企业', link: '/enterprises/building-materials' },
          ],
        },
      ],
    },

    search: {
      provider: 'local',
      options: {
        locales: {
          root: {
            translations: {
              button: {
                buttonText: '搜索文档',
                buttonAriaLabel: '搜索文档',
              },
              modal: {
                noResultsText: '无法找到相关结果',
                resetButtonTitle: '清除查询条件',
                footer: {
                  selectText: '选择',
                  navigateText: '切换',
                  closeText: '关闭',
                },
              },
            },
          },
        },
      },
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/' },
    ],

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026 装修知识库',
    },

    editLink: {
      pattern: 'https://github.com/your-repo/edit/main/docs/:path',
      text: '在 GitHub 上编辑此页',
    },

    lastUpdated: {
      text: '最后更新于',
      formatOptions: {
        dateStyle: 'full',
        timeStyle: 'medium',
      },
    },

    docFooter: {
      prev: '上一页',
      next: '下一页',
    },

    outline: {
      label: '页面导航',
    },
  },

  head: [
    ['meta', { name: 'keywords', content: '装修,家装,施工规范,验收标准,装修避坑,装修报价,装修材料' }],
    ['meta', { name: 'author', content: '装修知识库' }],
    // Open Graph / 微信分享卡片
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:title', content: '装修知识库' }],
    ['meta', { property: 'og:description', content: '335篇装修知识文章，覆盖国标解读、施工规范、验收清单、避坑指南、市场分析，为从业者和业主提供专业参考' }],
    ['meta', { property: 'og:image', content: 'https://zhuangxiuzhishi.cn/og-cover.svg' }],
    ['meta', { property: 'og:url', content: 'https://zhuangxiuzhishi.cn/' }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    // PWA
    ['link', { rel: 'manifest', href: '/manifest.json' }],
    ['meta', { name: 'theme-color', content: '#3B82F6' }],
    ['meta', { name: 'apple-mobile-web-app-capable', content: 'yes' }],
    ['meta', { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' }],
    // 百度统计
    ['script', {}, `var _hmt = _hmt || []; (function() { var hm = document.createElement("script"); hm.src = "https://hm.baidu.com/hm.js?0c9c1ef25610fa1a45227942f16d07fd"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s); })();`],
  ],
})
